#!/bin/sh

# boot from Tarbel FDC with external boot ROM

rm -f disks/drive[abc].dsk
ln disks/library/ucsd-i5-1.dsk disks/drivea.dsk
ln disks/library/ucsd-i5-2.dsk disks/driveb.dsk
ln disks/library/ucsd-i5-interp.dsk disks/drivec.dsk

./altairsim $*
