#!/bin/sh

rm -f disks/hd0.hdd disks/drivea.dsk
ln disks/library/cromix_work.dsk disks/drivea.dsk
ln disks/library/cromix_work.hdd disks/hd0.hdd

BOOTENV=`sed '/^#/d;s/#.*$//;' conf/boot.conf | xargs`

env $BOOTENV ./cromemcosim -M1 -R $*
